services:
  - type: web
    name: eventhive-app
    env: python
    runtime: python-3.11
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 2 --worker-class sync --timeout 60 --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: FLASK_ENV
        value: production
