"""Add attended status to registrations

Revision ID: e11b61d54034
Revises: 3dc89d4cc1b7
Create Date: 2025-10-20 23:12:45.072728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e11b61d54034'
down_revision = '3dc89d4cc1b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('attended', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('registrations', schema=None) as batch_op:
        batch_op.drop_column('attended')

    # ### end Alembic commands ###
